ALTER TYPE "LotteryConditionType" ADD VALUE IF NOT EXISTS 'USER_POST_COUNT';
ALTER TYPE "LotteryConditionType" ADD VALUE IF NOT EXISTS 'DAILY_POST_COUNT';
ALTER TYPE "LotteryConditionType" ADD VALUE IF NOT EXISTS 'DAILY_COMMENT_COUNT';
